[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "differ hub burst hybrid wait risk problem divert stand soft picnic mask type battle mind this tragic ivory possible desert monkey impulse ten toast"
